apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume-app1
          mountPath: /usr/share/nginx/html # mounted as simple volume, other files will be not seen
      volumes:
      - name: html-volume-app1
        configMap:
          name: app1