FROM		alpine:latest
MAINTAINER	sschmele <sschmele@student.21-school.ru>

RUN			apk add vim

ENTRYPOINT	vim

#building an image: 		docker build -t 00 . (the point in the end shows the directory)
#running the container: 	docker run -it 00 (in the interactive mode you should \
#							enter the container within vim)
#exiting the container:		esc + ':' + "q!"
