apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ new_nalue_while_evaluation }}
    targetRevision: HEAD
    path: default
  destination: 
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
