apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-project
  labels:
    app: iot
spec:
  description: ArgoCD Project to deploy app
  sourceRepos:
    - https://gitlab.192.168.59.100.nip.io/gitlab-instance-9854ee8a/*
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
  orphanedResources:
    warn: false

