# -*- mode: ruby -*-
# vi: set ft=ruby :

### configuration parameters ###
# amount of RAM for VM
VM_RAM_MB = 1024
# number of CPUs for VM
VM_CPU_COUNT = 1
# server k3s cluster name
K3S_SERVER_NAME = "dwisokyS"
# server k3s cluster ip-address
K3S_SERVER_IP = "192.168.42.110"
# server k3s cluster port
K3S_SERVER_PORT = 6443
# worker k3s cluster name
K3S_WORKER_NAME = "dwisokySW"
# server k3s cluster ip-address
K3S_WORKER_IP = "192.168.42.111"
### /configuration parameters ###

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = 'vm_centos_7'
  config.vm.box_url = 'file:///Users/a18979859/school_21/CentOS-7-x86_64-Vagrant-2004_01.VirtualBox.box'
  config.vm.box_check_update = false
  config.vm.synced_folder "confs/", "/tmp/p1", type: "virtualbox"

  config.vm.define K3S_SERVER_NAME do |server|
    server.vm.hostname = K3S_SERVER_NAME
    server.vm.network "private_network", ip: K3S_SERVER_IP, virtualbox__intnet: true
    server.vm.provider "virtualbox" do |vm_centos_7|
      vm_centos_7.check_guest_additions = false
      vm_centos_7.customize ["modifyvm", :id, "--name", K3S_SERVER_NAME]
      vm_centos_7.name = K3S_SERVER_NAME
      vm_centos_7.cpus = VM_CPU_COUNT
      vm_centos_7.memory = VM_RAM_MB
    end
    server.vm.provision "shell" do |server|
      server.path = "scripts/prepare_server_vm.sh"
      server.args = [K3S_SERVER_IP]
    end
  end

  # config.vm.provision "shell", inline: "vagrant ssh -c \"sudo cat /var/lib/rancher/k3s/server/node-token\" > ~/token.txt"

  config.vm.define K3S_WORKER_NAME do |worker|
    worker.vm.hostname = K3S_WORKER_NAME
    worker.vm.network "private_network", ip: K3S_WORKER_IP, virtualbox__intnet: true
    worker.vm.provider "virtualbox" do |vm_centos_7|
      vm_centos_7.check_guest_additions = false
      vm_centos_7.customize ["modifyvm", :id, "--name", K3S_WORKER_NAME]
      vm_centos_7.name = K3S_WORKER_NAME
      vm_centos_7.cpus = VM_CPU_COUNT
      vm_centos_7.memory = VM_RAM_MB
    end
    worker.vm.provision "shell" do |worker|
      worker.path = "scripts/prepare_worker_vm.sh"
      worker.args = [K3S_WORKER_IP, K3S_SERVER_IP, K3S_SERVER_PORT]
    end
  end
end
